# Default values for c#.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.39.247.206:5000/tmeulensteen/jx-quickstart
  tag: 0.0.1
  pullPolicy: IfNotPresent
service:
  name: jx-quickstart
  type: ClusterIP
  externalPort: 5000
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
